"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { apiFetch, explainError } from "./lib/api";

export default function OverviewPage() {
  const [ready, setReady] = useState<boolean | null>(null); const [error, setError] = useState("");
  useEffect(() => { apiFetch<{ status?: string }>("/ready").then((body) => setReady(body.status === "ready")).catch((reason) => { setReady(false); setError(explainError(reason)); }); }, []);
  return <main className="px-5 py-10 sm:px-8 lg:px-12 lg:py-16"><div className="mx-auto max-w-6xl"><div className="max-w-3xl"><p className="eyebrow">Research workspace</p><h1 className="mt-3 text-4xl font-bold tracking-tight text-ink sm:text-5xl">Turn a research question into a reviewable synthetic cohort.</h1><p className="mt-5 text-lg leading-8 text-slate-600">OncoAgent helps researchers define bounded cohort criteria, gather structured evidence, and prepare a research brief for a separate human reviewer.</p></div><div className="mt-8 flex flex-wrap gap-3"><Link href="/workflow" className="rounded-xl bg-ink px-5 py-3 text-sm font-semibold text-white shadow-sm hover:bg-slate-800">Start a research workflow</Link><Link href="/runs" className="rounded-xl border border-slate-300 bg-white px-5 py-3 text-sm font-semibold text-slate-700">View my runs</Link></div><div className="mt-12 grid gap-5 md:grid-cols-3"><article className="card"><p className="eyebrow">01 · Define</p><h2 className="mt-3 text-lg font-bold">Set the question and criteria</h2><p className="mt-2 text-sm leading-6 text-slate-600">Choose the bounded dataset, clarify inclusion criteria, and cap the candidate set.</p></article><article className="card"><p className="eyebrow">02 · Investigate</p><h2 className="mt-3 text-lg font-bold">Trace structured evidence</h2><p className="mt-2 text-sm leading-6 text-slate-600">Follow progress from planning through candidate retrieval and FHIR-linked verification.</p></article><article className="card"><p className="eyebrow">03 · Review</p><h2 className="mt-3 text-lg font-bold">Hand off for approval</h2><p className="mt-2 text-sm leading-6 text-slate-600">A separate reviewer must approve the synthetic research brief before it is finalized.</p></article></div><div className="mt-8 grid gap-5 lg:grid-cols-[1fr_320px]"><section className="rounded-2xl border border-amber-200 bg-amber-50 p-6 text-sm leading-6 text-amber-950"><strong>Synthetic data boundary.</strong> This demonstration uses synthetic Synthea data only. Results are not clinical recommendations and the platform is not clinically validated.</section><section className="card"><div className="flex items-center justify-between"><h2 className="font-bold">Platform readiness</h2><span className={`status ${ready ? "status-good" : "status-warn"}`}>{ready === null ? "Checking" : ready ? "Ready" : "Unavailable"}</span></div><p className="mt-3 text-sm text-slate-600">{error || (ready ? "The API and database are ready for a local demonstration." : "Start FastAPI and verify the local database before running a workflow.")}</p></section></div></div></main>;
}
