"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";

const apiBase = process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8000";
type Dataset = { id: string; name: string; imported_patient_count?: number };
type Run = { run_id: string; status: string; current_node: string; planner_lineage?: Record<string, unknown>; structured_plan?: Record<string, unknown>; warnings: string[]; errors: string[] };

export default function WorkflowPage() {
  const [datasets, setDatasets] = useState<Dataset[]>([]); const [datasetId, setDatasetId] = useState(""); const [request, setRequest] = useState(""); const [planner, setPlanner] = useState("auto"); const [run, setRun] = useState<Run | null>(null); const [message, setMessage] = useState(""); const [modelStatus, setModelStatus] = useState<Record<string, unknown> | null>(null);
  useEffect(() => { Promise.all([fetch(`${apiBase}/api/v1/datasets`).then((r) => r.json()), fetch(`${apiBase}/api/v1/models/local-runtime`).then((r) => r.json())]).then(([d, m]) => { setDatasets(d); setDatasetId(d[0]?.id ?? ""); setModelStatus(m.status ?? m); }).catch(() => setMessage("Backend unavailable.")); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); setMessage("Starting governed workflow…"); try { const response = await fetch(`${apiBase}/api/v1/runs`, { method: "POST", headers: { "content-type": "application/json", "X-Actor-Id": "researcher-console", "X-Actor-Role": "researcher" }, body: JSON.stringify({ dataset_id: datasetId, request, planner_provider: planner, max_candidates: 20 }) }); const body = await response.json(); if (!response.ok) throw new Error(body.detail ?? "Run failed"); setRun(body); setMessage("Workflow started. It will pause before finalization for reviewer approval."); } catch (error) { setMessage(error instanceof Error ? error.message : "Workflow failed."); } }
  return <main className="min-h-screen px-5 py-8 sm:px-8 lg:px-12"><div className="mx-auto max-w-6xl"><Link className="text-sm font-semibold text-teal" href="/">← Overview</Link><p className="mt-8 text-sm font-semibold uppercase tracking-[0.18em] text-teal">Workflow Console</p><h1 className="mt-2 text-3xl font-bold text-ink">Governed cohort planning</h1><div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-950"><strong>Synthetic development workflow.</strong> Human approval is mandatory; this platform is not clinically validated.</div><form onSubmit={submit} className="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><label className="block text-sm font-semibold text-ink" htmlFor="dataset">Dataset</label><select id="dataset" className="mt-2 w-full rounded border border-slate-300 p-3" value={datasetId} onChange={(e) => setDatasetId(e.target.value)}>{datasets.map((d) => <option key={d.id} value={d.id}>{d.name} ({d.imported_patient_count ?? "?"} patients)</option>)}</select><label className="mt-4 block text-sm font-semibold text-ink" htmlFor="request">Research request</label><textarea id="request" required minLength={5} className="mt-2 min-h-28 w-full rounded border border-slate-300 p-3" value={request} onChange={(e) => setRequest(e.target.value)} placeholder="Find synthetic adults with hypertension and elevated blood pressure."/><div className="mt-4 flex flex-wrap items-end gap-4"><label className="text-sm font-semibold text-ink">Planner<select className="mt-2 block rounded border border-slate-300 p-2" value={planner} onChange={(e) => setPlanner(e.target.value)}><option value="auto">Local Qwen with deterministic fallback</option><option value="qwen_local">Local Qwen</option><option value="deterministic">Deterministic</option></select></label><button className="rounded bg-ink px-5 py-3 font-semibold text-white" type="submit">Create run</button></div></form>{modelStatus && <p className="mt-4 text-sm text-slate-600">Local model: {String(modelStatus.healthy ? "available" : "unavailable; deterministic fallback remains available")} · qwen3:8b is never loaded in FastAPI.</p>}{message && <p role="status" className="mt-4 rounded bg-slate-100 p-3 text-sm">{message}</p>}{run && <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold text-ink">Run {run.run_id}</h2><p className="mt-2 text-sm">Status: <strong>{run.status}</strong> · Node: {run.current_node}</p><p className="mt-2 text-sm">Planner: {String(run.planner_lineage?.provider_id ?? "deterministic fallback")}</p>{run.structured_plan && <pre className="mt-4 overflow-auto rounded bg-slate-950 p-4 text-xs text-slate-100">{JSON.stringify(run.structured_plan, null, 2)}</pre>}<Link className="mt-4 inline-block font-semibold text-teal" href={`/runs/${run.run_id}`}>Open run details →</Link></section>}</div></main>;
}
