"use client";

import { useEffect, useState } from "react";
import Link from "next/link";

const apiBase = process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8000";
type Agent = { agent_id: string; name: string; framework: string; framework_version: string; role: string; risk_tier: string; tools: string[]; approval_policy: Record<string, unknown>; recovery: Record<string, unknown>; status: string; known_limitations: string[] };

export default function AgentCatalogPage() {
  const [agents, setAgents] = useState<Agent[]>([]);
  const [error, setError] = useState(false);
  useEffect(() => { fetch(`${apiBase}/api/v1/agents`, { headers: { "X-Actor-Id": "catalog-console", "X-Actor-Role": "admin" } }).then((r) => { if (!r.ok) throw new Error("unavailable"); return r.json(); }).then((body) => setAgents(body.items ?? [])).catch(() => setError(true)); }, []);
  return <main className="min-h-screen px-5 py-8 sm:px-8 lg:px-12"><div className="mx-auto max-w-6xl"><Link className="text-sm font-semibold text-teal" href="/">← Overview</Link><h1 className="mt-8 text-3xl font-bold text-ink">Unified Agent Catalog</h1><p className="mt-3 text-slate-600">Framework-neutral registry for governed first-party workflows and downstream MCP consumers.</p><div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-950">Synthetic Synthea data only. Not clinically validated. Development identity simulation is not production authentication.</div>{error && <p role="alert" className="mt-5 rounded bg-red-50 p-4 text-red-800">Agent registry unavailable.</p>}<div className="mt-6 grid gap-5 md:grid-cols-2">{agents.map((agent) => <article key={agent.agent_id} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-3"><h2 className="text-xl font-bold text-ink">{agent.name}</h2><span className="rounded-full bg-slate-100 px-2 py-1 text-xs">{agent.status}</span></div><dl className="mt-5 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="font-semibold">Framework</dt><dd>{agent.framework} {agent.framework_version}</dd></div><div><dt className="font-semibold">Role</dt><dd>{agent.role}</dd></div><div><dt className="font-semibold">Risk tier</dt><dd>{agent.risk_tier}</dd></div><div><dt className="font-semibold">Approval</dt><dd>{String(agent.approval_policy.required)}</dd></div><div><dt className="font-semibold">Recovery</dt><dd>{String(agent.recovery.mode)}</dd></div><div><dt className="font-semibold">Tools</dt><dd>{agent.tools.join(", ")}</dd></div></dl><p className="mt-5 text-sm text-slate-600">Limitations: {agent.known_limitations.join(" · ")}</p>{agent.framework === "CrewAI" && <Link className="mt-4 inline-block font-semibold text-teal" href="/crewai">Open CrewAI console →</Link>}</article>)}</div></div></main>;
}
